spring:
    application:
      name: quiz
    profiles:
      active: dev
    jpa:
      open-in-view: false
lingosphinx:
  gamification:
    client:
      api-key: ${GAMIFICATION_API_KEY}
      url: ${GAMIFICATION_CLIENT_URL}